var suggestions = [
    {name: "Chevrolet Onix Joy", prodID:"Chevrolet", description: "Generación 2019, variedad de colores. Motor 1.0, ideal para ciudad."},
    {name: "Fiat Way", prodID:"Fiat", description: "La versión de Fiat que brinda confort y a un precio accesible."},
    {name: "Suzuki Celerio", prodID:"Suzuki", description: "Un auto que se ha ganado la buena fama por su economía con el combustible."},
    {name: "Peugeot 208", prodID:"Peugeot", description: "El modelo de auto que se sigue renovando y manteniendo su prestigio en comodidad."},
    {name: "Bugatti Chiro", prodID:"Bugatti", description: "El mejor hiperdeportivo de mundo. Producción limitada a 500 unidades."},
    {name: "Oso de Peluche", prodID:"Peluche", description: "Oso de peluche gigante, con el bebé. Resistente y lavable. Tus hijos lo amarán."},
    {name: "Pelota de Básquetbol", prodID:"Pelota", description: "Balón de baloncesto profesional, para interiores, tamaño 5, 27.5 pulgadas. Oficial de la NBA."},
    {name: "Playstation 5", prodID:"Play5", description: "Maravíllate con increíbles gráficos y disfruta de nuevas funciones de PS5. Con E/S integrada."},
    {name: "Bicicleta", prodID:"Bicicleta", description: "¡La mejor BMX pequeña del mercado! Frenos traseros y cuadro duradero de acero Hi-Ten."},
    {name: "Juego de Comedor", prodID:"JuegoComedor", description: "Un conjunto sencillo y sólido, ideal para zonas de comedor pequeñas, hecho en madera maciza de pino."},
    {name: "Sofá", prodID:"Sofá", description: "Cómodo sofá de tres cuerpos, con chaiselongue intercambiable. Ideal para las siestas."},
    {name: "Armario", prodID:"Armario", description: "Diseño clásico con puertas con forma de panel. Espejo de cuerpo entero para ver cómo te queda la ropa."},
    {name: "Mesa de Centro", prodID:"Mesa", description: "Añade más funciones a tu sala de estar, ya que te permite cambiar fácilmente de actividad."},
 ];